### ISSUE TITLE
Could not find public constructor with ConnectionSource and optional Class parameters class ...  Missing static on class?

### ISSUE THREAD

**Issue by harside** [j256/ormlite-android#109]
```
java.sql.SQLException: Could not find public constructor with ConnectionSource and optional Class parameters class ...utils.dao.CustomDao.  Missing static on class?
 at com.j256.ormlite.dao.DaoManager.createDao(DaoManager.java:86)
 at com.j256.ormlite.android.apptools.OrmLiteSqliteOpenHelper.getDao(OrmLiteSqliteOpenHelper.java:277)
```

This error appears when the apk is generated.

**Comment by noordawod** [comment]
Missing static on class? 😄 

Please follow instructions: http://ormlite.com/javadoc/ormlite-core/doc-files/ormlite_1.html

**Comment by harside** [comment]
I was using a custom Dao class, this class is not necessary?

**Comment by noordawod** [comment]
You can use a custom Dao class, but you have to define a static property on it. Read the instructions mentioned above.

**Comment by PrideFafy** [comment]
I followed the instructions but I'm still getting an error. Maybe I'm missing the static property meaning. I did this on the entity class:
@DatabaseTable( daoClass = AdministratorDaoImpl.class)
