### ISSUE TITLE
can't find referenced class javax.persistence.Column

### ISSUE THREAD

**Issue by jubincn** [j256/ormlite-android#110]
After upgrading ormlite from 4.48 to 5.1, I met javax.persistent related warnings when assemble a realease version. The logs is like this:
```
Warning: com.j256.ormlite.misc.JavaxPersistenceImpl: can't find referenced class javax.persistence.Column
```
Add ```-dontwarn javax.persistence.**``` to proguard rules can resolve it, but I wander if this is a 
 recommended way.

**Comment by j256** [comment]
Sorry for the delay.  This seems like a Proguard issue so I think your solution is correct.  The `JavaxPersistenceImpl` is an optional class which references the `javax.persistence.*` annotations so I can see this warning being emitted if it was looking at all classes.
