### ISSUE TITLE
IllegalStateException: attempt to re-open an already-closed object

### ISSUE THREAD

**Issue by me73123** [j256/ormlite-android#112]
I have an error "IllegalStateException: attempt to re-open an already-closed object" in multi thread by android 9.0.

I closed the connectionSource in each query.
like this:
```
ConnectionSource cs = cf.getConnectionSource();
try {
    UserDao userDao = new UserDao(cs);
    userDao.deleteAll();
} catch (Exception e) {
    throw e;
} finally {
    try {
        cs.close();
    } catch (SQLException e) {
        logger.error("Exception:" + e);
    }
}
```

Any ideas?

**Comment by noordawod** [comment]
Why are you closing the connection source?

**Comment by me73123** [comment]
The connection will be closed after each query because the connection source may not be used later.

**Comment by me73123** [comment]
I solved this problem.
I closed the connectionSource before get connection source.

**Comment by me73123** [comment]
I solved this problem.
I closed the connectionSource before get connection source.

**Comment by j256** [comment]
Any idea why the old version didn't suffer from this problem?

**Comment by me73123** [comment]
I just reconfirmed whether an old version of android has encountered this problem.
It seems that the same problem will arise.

**Comment by siyinngduo** [comment]
When can close be called?
