### ISSUE TITLE
How to ignore ormlite logs?

### ISSUE THREAD

**Issue by me73123** [j256/ormlite-android#113]
I get a lot of SQL logs with ormlite version 5.1.
In the 4.4 version, there is no such log.
But I will also use LoggerFactory.getLogger() in my project. 
How can I hide only the log of ormlite?

Logs like this:
```
D/com.j256.ormlite.stmt.StatementExecutor: 43, query-for-first of 'SELECT * FROM `profileimg` WHERE `owneruuid` = 'aabbcc' ' returned at 0 results
D/com.j256.ormlite.stmt.StatementBuilder: 43, built statement SELECT * FROM `profileimg` WHERE `owneruuid` = 'aabbcc' 
D/com.j256.ormlite.stmt.mapped.BaseMappedStatement: 43, prepared statement 'SELECT * FROM `profileimg` WHERE `owneruuid` = 'aabbcc' ' with 0 args
```

**Comment by j256** [comment]
Which `LoggerFactory` is that? `com.j256.ormlite.logger.LoggerFactory`?  Then it depends on which `Logger` you are using.  My `LocalLog` allows you to set the `com.j256.ormlite.logger.level` to something like `WARN` to turn off those logs.   The thing is that you need to do this as soon as possible in your main or launching class.  What is missing is a `LocalLog.setGlobalLevel(...)` method.  I'll add it.

If you are using another logging system (like log4j, slf4j, etc.) then you'll need to figure out how they are configured.

**Comment by me73123** [comment]
I tried the `System.setProperty(LocalLog.LOCAL_LOG_LEVEL_PROPERTY, "ERROR")` or `System.setProperty(LocalLog.LOCAL_LOG_LEVEL_PROPERTY, "error")` setting but it didn't work.Can you give me an example?
Also, if I want to use ormliteLocalLog.properties to set, where should the file be placed in the project?

**Comment by j256** [comment]
In 5.2 I added a [`Logger.setGlobalLogLevel(...)` method](https://ormlite.com/javadoc/ormlite-core/com/j256/ormlite/logger/Logger.html#setGlobalLogLevel-com.j256.ormlite.logger.Log.Level-) which can be called early in your application to disable (or tune the level) of all logs.  I also added an [`OFF` level](https://ormlite.com/javadoc/ormlite-core/com/j256/ormlite/logger/Log.Level.html#OFF) to be able to turn off log messages.

I've just added a `NullLog` log implementation as well that will be in 5.4.  See: https://github.com/j256/ormlite-core/commit/e0103eed441ff4fe74b15805e4013896c2ba4853
