### ISSUE TITLE
ORMLite Android - Prevent Upgrade inside catch

### ISSUE THREAD

**Issue by Murded** [j256/ormlite-android#115]
I'm trying find a way to prevent the database version from updating in the event that something goes wrong inside the ```onUpgrade``` method.

I have the following helper class

```
public class DatabaseHelper extends OrmLiteSqliteOpenHelper
{
   private DatabaseHelper(Context context)
   {
      super(context, DATABASE_NAME, null, DATABASE_VERSION, R.raw.ormlite_config);
   }

   @Override
   public void onUpgrade(SQLiteDatabase db, ConnectionSource connectionSource, int oldVersion, int newVersion)
   {
       try
       {
         MigrationHelper.RunMigrations(mContext,oldVersion,this);
       }
       catch (Exception e)
       {
            //How can I prevent the version from updating if the migration fails?
       }
    }
}

```

Prefferably I want to be able to show a message dialog to the user so just throwing an unhandled exception (that would cause the application to crash) isn't really ideal.

Thanks in advance

**Comment by j256** [comment]
Can you add some comments to help others @Murded ?

**Comment by Murded** [comment]
@j256 I've updated my original post, if you have any suggestions / issues with my solution please let me know
