### ISSUE TITLE
Is there any way we can get a 5.2 release to benefit from a bugfix in core 5.2?

### ISSUE THREAD

**Issue by darobarts** [j256/ormlite-android#119]
We are dealing with a NullPointerException exactly as described in this issue: https://github.com/j256/ormlite-core/issues/135 

The extra logging to figure out which values are coming in null would be incredibly valuable to unblock us. Any way we can get the 5.2 release which contains the fix mentioned in that issue?

**Comment by j256** [comment]
5.2 and 5.3 have been released.  FYI.
