### ISSUE TITLE
Better integrated OrmLiteConfigUtil 

### ISSUE THREAD

**Issue by green-coder** [j256/ormlite-android#18]
The way the class OrmLiteConfigUtil is working is quite hacky, it requires both the source code and the class files.

There are better alternatives nowadays:
- It can be implemented as a standard [annotation processor](http://docs.oracle.com/javase/7/docs/api/javax/annotation/processing/Processor.html), taking the class files as input.
- It can be implemented very easily as a Java source parser, using the [QDox](http://qdox.codehaus.org/) library, taking the java source file as input.

The later solution is pretty useful for the Android : it doesn't require to compile the files first and can be easily integrated into a Gradle build (i.e. this can be implemented as a task executed before the app's resources are processed by the Android plugin, far before the compilation of the source code takes place).

I am willing to implement the second solution as a contribution to the project. Are you going to integrate it to the project?

**Comment by j256** [comment]
Sorry that I never responded to this.  I don't have a lot of experience with either solution.  One thing we are considering is to add a feature that writes the config.txt file at startup to cache the annotation information for the life of the application on the device.
