### ISSUE TITLE
timestamp type can not be assigned

### ISSUE THREAD

**Issue by ggaaooppeenngg** [j256/ormlite-android#19]
`java.sql.SQLException: Could not assign object 'Thu Aug 07 11:09:25 EDT 2014' to field FieldType:name=created_time,class=Homework`

I got this warming when I query "Homeworks"

and I define my created_time as

```
public class Homework {
	@DatabaseField(generatedId = true)
	private Integer id;
	@DatabaseField
	private String URI;
	@DatabaseField
	private Integer assignment_id;
	@DatabaseField(dataType = DataType.TIME_STAMP, format = "yyyy-MM-dd HH:mm:ss")
	private Timestamp created_time;
	@DatabaseField
	private String title;
}
```

I searched for stackoverflow and tried some solutions but did work it out.

**Comment by j256** [comment]
I've added the type in the error message that would have helped with this.  In your code, any chance you were using something other than a `java.sql.Timestamp`?

**Comment by j256** [comment]
I'm going to close for now.
