### ISSUE TITLE
OrmLite and AutoValue union

### ISSUE THREAD

**Issue by tomkoptel** [j256/ormlite-android#21]
First of all, thanks for great library :)

My question is follow...Is there any way to combine together OrmLite with [AutoValue](https://github.com/google/auto/tree/master/value) ?

Best regards.

**Comment by j256** [comment]
Sorry for the delay on this.  I [unfortunately] have no experience with AutoValue.  Did you make any progress on your own?

**Comment by hanibalsk** [comment]
Me either. Should be usefull to use autovalue with ormlite

**Comment by j256** [comment]
I'm going to close this for now but feel free to reopen if you have more details.
