### ISSUE TITLE
Android Gingerbread INSTALL_FAILED_DEXOPT 

### ISSUE THREAD

**Issue by viper123** [j256/ormlite-android#29]
We are developing an application, and when we use this library we get INSTALL_FAILED_DEXOPT. This behavior is happening only on Gingerbread. In logcat we get this erorr:
LinearAlloc exceeded capacity (5242880), last=4108
After we've done some research on this mater we found that has something to do with how complex the application is using abstractizations (abstract classes and interfaces).
https://code.google.com/p/android/issues/detail?id=22586

**Comment by j256** [comment]
Sorry for the delay.  Any more details on this problem?  We are getting ready to [finally] push 4.49 and I'd like to make sure this isn't an issue.
