### ISSUE TITLE
Add ActionBarActivity

### ISSUE THREAD

**Issue by gsingh93** [j256/ormlite-android#37]
When I make a new project the default activity is an `ActionBarActivity`. However, to use OrmLite I have to change this to an OrmLite specific activity. Can an OrmLite activity be created that inherits from `ActionBarActivity`?

I've currently copied and pasted the `OrmLiteBaseActivity` code into a new class that extends `ActionBarActivity` as a workaround.

**Comment by kpgalligan** [comment]
Well, we *could* add that, but I'm trying to deprecate the whole base activity thing.  You don't need them.  Essentially, create a singleton for your db helper.  http://stackoverflow.com/a/3689883

**Comment by kpgalligan** [comment]
To follow up, don't extend the activity classes in ormlite.
