### ISSUE TITLE
 a bug

### ISSUE THREAD

**Issue by agoodcoolman** [j256/ormlite-android#47]
in android,if I insert a String into datebase with symbol    '    
when  i query it, it tell me wrong. without the symbol,it working

**Comment by j256** [comment]
This is a FAQ.  You should use the SelectArg class to query for things with quotes.  See http://ormlite.com/docs/select-arg .  If you are saying that you inserted a string using dao.create(...) and it didn't make it into the database then please reopen this issue.

**Comment by agoodcoolman** [comment]
e....tks,
