### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Could not find appropriate get method for private XXX.id

### ISSUE THREAD

**Issue by jianinz** [j256/ormlite-android#53]
Hi,

I am encountering this exception which i don't understand.
````
Caused by: java.lang.IllegalArgumentException: Could not find appropriate get method for private 
java.lang.String com.xx.xx.xx.json.XXX.id
````
In my XXX pojo, getId method was defined, so i don't understand why this happens, anyone could shed some light on it? 

~~~~java
    @DatabaseField(columnName = Table.Columns.ID, id = true, useGetSet = true, unique = true)
    private String id;

    public String getId() {
        return aggregateStart.getTime() + "-" + aggregateEnd.getTime() + "-" + aggregateInterval;
    }

    public void setId(final String id) {
        this.id = id;
    }
~~~~

is id not allowed as String instead of int? or getId cannot return concatenated string?
Thanks!

**Comment by j256** [comment]
Any chance the class is not static or not public or something?  Are those methods in a base class or the entity class itself?

**Comment by jianinz** [comment]
Thanks for input. But not really, it's not a base class, neither static. any other suggestions?

**Comment by j256** [comment]
Is this an inner class?

**Comment by jianinz** [comment]
no, it's not. 
Although the column annotation in id is a static class, but i am not sure that is what you referred to
`    @DatabaseField(columnName = Table.Columns.ID, id = true, useGetSet = true, unique = true)`

**Comment by j256** [comment]
Huh.  I'm stumped.  I was asking about inner classes and the like because reflection can't see the methods unless the inner class is static and visible.  Can you whittle down your entity and post it to pastebin.com or something?  I'd like to see if I can reproduce it.

**Comment by jianinz** [comment]
Sure, thanks

http://pastebin.com/Kyd7QPxT

**Comment by j256** [comment]
This passes for me:  http://pastebin.com/fcJfXJuB

**Comment by jianinz** [comment]
Thanks. In our productuon app, we have found only few users had experienced this crash. I never experienced this crash neither myself.

**Comment by j256** [comment]
I'm going to close but feel free to re-open if you get more information.

**Comment by jianinz** [comment]
alright, thanks!

**Comment by jianinz** [comment]
think i have found something.
If json entity has been obfuscated by proguard, this could happen. By prevent from happening, just add the following in the proguard
~~~~java
-keep public class com.app.example.foo.bar.ReportSummary {
    public protected private *;
}
~~~~

**Comment by joezorry** [comment]
@jianinz guessing this issue should be closed then?

**Comment by joezorry** [comment]
@jianinz good find.

**Comment by jianinz** [comment]
Thanks @joezorry :)

**Comment by rAseri** [comment]
Hi guys, i'm faced with same issue. 
In our dev envirenment all works fine, but on production we have some users with crashes: **java.lang.IllegalArgumentException: Could not find appropriate get method for private XXX.id.**
This issue happens only on Samusung devices, but i'm tested app on Samsung Galaxy S5 and it's works fine. I can't even simulate this crach and I don't understand how to fix it.

This is carchlytics logs: http://crashes.to/s/13fc0337145
This is part of my POJO class: http://pastebin.com/D37AF8ZB

**Comment by jianinz** [comment]
Hi @rAseri , the previous solution did not work out for me neither, sorry, i forgot to update my answer. In the end, i did a workaround, instead of doing following
~~~~java
    @DatabaseField(columnName = Table.Columns.ID, id = true, useGetSet = true, unique = true)
    private String id;

    public String getId() {
        return aggregateStart.getTime() + "-" + aggregateEnd.getTime() + "-" + aggregateInterval;
    }

    public void setId(final String id) {
        this.id = id;
    }
~~~~
i don't use `useGetSet` annotation anymore, so to avoid reflection. I used normal incremental id
~~~~java

    @DatabaseField(columnName = ID, index = true, generatedId = true)
    private Integer id;

    public Integer getId() {
        return id;
    }

    public void setId(final Integer id) {
        this.id = id;
    }
~~~~
and just add another column to do your customization

**Comment by lostmsu** [comment]
I experience this bug on some machines as well, but only on fields, which start with 'i'. I guess it has something to do with first letter capitalization not being language-neutral.

**Comment by j256** [comment]
Aha.  Ok.  I think I've fixed this by adding a `DatabaseType.upCaseEntityName()` with the default implementation using: `entityName.toUpperCase(Locale.ENGLISH);`
See: https://github.com/j256/ormlite-core/commit/8ccc75d7479f33ea99f8b0a3bed3b934ecdd757c
