### ISSUE TITLE
Is there a way to create multiples tables based on one simple class?

### ISSUE THREAD

**Issue by alemedero** [j256/ormlite-android#58]
I have a library project, with common functionalities and then i have multiple projects that depends on it.

Is there a way, for example, from one class "ArticleDTO" create multiple tables representing the categories that i have in each app?

Can i achieve this by using the table config file?

**Comment by xtien** [comment]
Can you elaborate a little? Ormlite is an ORM tool that stores your objects in a database. I don's see how you can split up an object to store it in multiple tables without splitting up the class itself.

**Comment by kpgalligan** [comment]
Short answer is "no". Going to close this.
