### ISSUE TITLE
column not found in micromax

### ISSUE THREAD

**Issue by vinod1054** [j256/ormlite-android#60]
I am getting the following exception only on Micromax A350.
**Exception: java.lang.IllegalArgumentException: Unknown column name 'xyzcolumn' in table abctable**
I am using progaurd and i have added the progaurd rules for ormlite, but still problem persists.
This is happening when I generated apk from linux machine.

**Comment by j256** [comment]
Sorry, I don't have any recommendations.  Maybe a proguard mailing list or SO?
