### ISSUE TITLE
order by FIELD?

### ISSUE THREAD

**Issue by agoodcoolman** [j256/ormlite-android#67]
I want use custom rules in order by.  how implement order by ：3  1  4  2

eg:
-----------------------
| status  |   value | 
-----------------------
|      A     |   1     | 
-----------------------
|     B     |   2      | 
-----------------------
|     C     |   3      | 
-----------------------
|      D    |   4      | 
-----------------------

**Comment by j256** [comment]
Can you flesh this question out?  I don't understand it.

**Comment by agoodcoolman** [comment]
I solved the problem.
just want custom sorting data

**Comment by j256** [comment]
Np @agoodcoolman.  So this can be closed?  Anything to add?

**Comment by agoodcoolman** [comment]
yes ,you can close~
