### ISSUE TITLE
java.lang.IllegalAccessError Class ref in pre-verified class resolved to unexpected implementation

### ISSUE THREAD

**Issue by yunfengsa** [j256/ormlite-android#68]
java.lang.IllegalAccessError
Class ref in pre-verified class resolved to unexpected implementation
java.lang.RuntimeException:An error occured while executing doInBackground()
android.os.AsyncTask$3.done(AsyncTask.java:300)
......
java.lang.IllegalAccessError:Class ref in pre-verified class resolved to unexpected implementation
java.lang.reflect.Method.getDefaultValue(Native Method)
java.lang.reflect.Method.getDefaultValue(Method.java:353)
libcore.reflect.AnnotationFactory.getElementsDescription(AnnotationFactory.java:75)
libcore.reflect.AnnotationFactory.<init>(AnnotationFactory.java:112)
libcore.reflect.AnnotationFactory.createAnnotation(AnnotationFactory.java:94)
java.lang.reflect.Field.getAnnotation(Native Method)
java.lang.reflect.Field.getAnnotation(Field.java:209)
com.j256.ormlite.field.DatabaseFieldConfig.com.j256.ormlite.field.DatabaseFieldConfig fromField(com.j256.ormlite.db.DatabaseType,java.lang.String,java.lang.reflect.Field)(DatabaseFieldConfig.java:503)

Some machines has throw that exeption,although I have keep the thread safe,waiting for help

**Comment by yunfengsa** [comment]
@j256

**Comment by xudjx** [comment]
> java.lang.IllegalAccessError
> Class ref in pre-verified class resolved to unexpected implementation
> java.lang.RuntimeException:An error occured while executing doInBackground()
> android.os.AsyncTask$3.done(AsyncTask.java:300)
> ......
> java.lang.IllegalAccessError:Class ref in pre-verified class resolved to unexpected implementation
> java.lang.reflect.Method.getDefaultValue(Native Method)
> java.lang.reflect.Method.getDefaultValue(Method.java:353)
> libcore.reflect.AnnotationFactory.getElementsDescription(AnnotationFactory.java:75)
> libcore.reflect.AnnotationFactory.(AnnotationFactory.java:112)
> libcore.reflect.AnnotationFactory.createAnnotation(AnnotationFactory.java:94)
> java.lang.reflect.Field.getAnnotation(Native Method)
> java.lang.reflect.Field.getAnnotation(Field.java:209)
> com.j256.ormlite.field.DatabaseFieldConfig.com.j256.ormlite.field.DatabaseFieldConfig fromField(com.j256.ormlite.db.DatabaseType,java.lang.String,java.lang.reflect.Field)(DatabaseFieldConfig.java:503)
> 
> Some machines has throw that exeption,although I have keep the thread safe,waiting for help

How this bug going? did you fix it?

**Comment by j256** [comment]
Sorry to not respond to this @yunfengsa .  Did you resolve the issue.

**Comment by yunfengsa** [comment]
> Sorry to not respond to this @yunfengsa . Did you resolve the issue.

sorry about that. this is not trouble me now.
