### ISSUE TITLE
java.sql.SQLException: Unknown field 'age' from the Android sqlite cursor, not in:[id, name]

### ISSUE THREAD

**Issue by Kilnn** [j256/ormlite-android#72]
Hello 
I upgrade my database and add one cloumn to the table 'user' . When i do CURD first time , i got this error.
This is my upgrade code in OrmLiteSqliteOpenHelper's subclass

> @Override
> public void onUpgrade(SQLiteDatabase database, ConnectionSource connectionSource, int oldVersion, int newVersion) {
>     if (oldVersion < 2) {
>         try {
>         Dao<User, Integer> dao = DaoManager.createDao(connectionSource, User.class);
>         dao.executeRaw("ALTER TABLE `user` ADD COLUMN age INTEGER;");
>         } catch (SQLException e) {
>         e.printStackTrace();
>         }
>     }
> }

**Comment by luaz** [comment]
Perhaps you forgot to run OrmLiteConfigUtil to regenerate ormlite_config.txt with the newly added field.

**Comment by j256** [comment]
I agree with @luaz .  Best of luck.
