### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Unknown column name 'deletedInServer' in table receivedpushid

### ISSUE THREAD

**Issue by leejegirl** [j256/ormlite-android#82]
Im using the ormlite-android v4.48.
I have found the error log.
08-04 12:10:59.135 W/System.err( 3054): Caused by: java.lang.IllegalArgumentException: Unknown column name 'deletedInServer' in table receivedpushid
08-04 12:10:59.135 W/System.err( 3054): 	at com.j256.ormlite.table.TableInfo.getFieldTypeByColumnName(SourceFile:155)
08-04 12:10:59.135 W/System.err( 3054): 	at com.j256.ormlite.stmt.Where.findColumnFieldType(SourceFile:681)

But deletedInServer column is in receivedpushid table.
Is this the ormlite issue?

**Comment by j256** [comment]
No it's not.  Maybe you need to update your database config file?
