### ISSUE TITLE
Remove OrmliteTransactionalProcessor (for now)

### ISSUE THREAD

**Issue by HaukeRa** [j256/ormlite-android#83]
It looks to me as if the class OrmliteTransactionalProcessor is not fully implemented (just printing some information)

Currently it breaks my tests because for any reason the AndroidInstrumentationRunner tries to access the class to see if it contains tests (but thats not directly ORMLite's fault).

I propose to put it into it's own package, since you need to use the annotationProcessor gradle directive to be able to use it anyways.

That also would be one less class needed to be listed in the proguard config to ignore.

**Comment by j256** [comment]
Yeah that was a mistake to check it in.  Removed.  Thanks.
