### ISSUE TITLE
update data use method createOrUpdate()

### ISSUE THREAD

**Issue by fylih** [j256/ormlite-android#99]
I have a problem  when update data use the method "createOrUpdate()" , everytime it create a new entry , but I just want to update a data

**Comment by j256** [comment]
Can you show some of the entities?  Have you tried to debug the database and the method to see what it is doing?

**Comment by fylih** [comment]
sorry, I am not set ID, this cause the issuse

**Comment by j256** [comment]
Figured.  So it can be closed?
